[package]
name = "remotefs-smb"
version = "0.4.1"
authors = ["Christian Visintin <christian.visintin@veeso.dev>"]
categories = ["network-programming"]
documentation = "https://docs.rs/remotefs-smb"
edition = "2024"
homepage = "https://veeso.github.io/remotefs-rs-smb/"
include = ["src/**/*", "examples/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["remotefs", "smb-client", "smb", "smb2", "smb3"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/remotefs-rs/remotefs-rs-smb"
rust-version = "1.88.0"
description = "remotefs SMB client library"

[dependencies]
log = "0.4"
remotefs = "^0.3"

[target."cfg(target_family = \"unix\")"]
[target."cfg(target_family = \"unix\")".dependencies]
libc = "0.2"
pavao = "0.3"

[target."cfg(target_family = \"windows\")"]
[target."cfg(target_family = \"windows\")".dependencies]
filetime = "0.2"
windows-sys = { version = "0.61", features = ["Win32_NetworkManagement_WNet", "Win32_Foundation"] }

[dev-dependencies]
anyhow = "^1"
argh = "0.1"
env_logger = "0.11"
pretty_assertions = "1"
rpassword = "7"
serial_test = "3"
tempfile = "3"

[features]
default = ["find"]
# misc
find = ["remotefs/find"]
no-log = ["log/max_level_off"]
vendored = ["pavao/vendored"]
# tests
with-containers = []

[package.metadata.docs.rs]
all-features = false
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "tree"
path = "examples/tree.rs"
